characters = [
    "Juliette",
    "Estelle",
    "Dubu",
    "Luna",
    "Juno",
    "Asher",
    "Kai",
    "Era",
    "X",
    "Aimi",
    "Finii",
    "Zentaro",
    "Octavia",
    "Vyce",
    "Mako",
    "Rune",
    "Drekar",
    "Atlas",
    "Nao",
    "Rasmus",
    "Kazan"
]
training_id_to_name_map = {
	"TD_BlessingShare": "Spark of Leadership",
	"TD_BlessingPower": "Spark of Strength",
	"TD_BlessingCooldownRate": "Spark of Focus",
	"TD_BlessingSpeed": "Spark of Agility",
	"TD_BlessingMaxStagger": "Spark of Resilience",
	"TD_SizeIncrease": "Built Different",
	"TD_SizeIncrease2": "Big Fish",
	"TD_Revive": "Recovery Drone",
	"TD_StackingSize": "Rampage",
	"TD_SizePowerConversion": "Might of the Colossus",
	"TD_BarrierBuff": "Demolitionist",
	"TD_StaggerPowerConversion": "Bulk Up",
	"TD_StaggerCooldownRateConversion": "Reverberation",
	"TD_StaggerSpeedConversion": "Peak Performance",
	"TD_CreationSize": "Monumentalist",
	"TD_CreationSizeLifeTime": "Timeless Creator",
	"TD_FasterProjectiles3": "Siege Machine",
	"TD_BuffAndDebuffDuration": "Cast to Last",
	"TD_FasterDashes2": "Chronoboost",
	"TD_SpecialCooldownAfterRounds": "Extra Special",
	"TD_EmpoweredHitsBuff": "Specialized Training",
	"TD_MovementAbilityCharges": "Twin Drive",
	"TD_PrimaryEcho": "Primetime",
	"TD_PrimaryAbilityCooldownReduction": "Rapid Fire",
	"TD_HitsReduceCooldowns": "Perfect Form",
	"TD_HitRockCooldown": "Hot Shot",
	"TD_ShrinkSelfGrowAllies": "Among Titans",
	"TD_StrikeRockTowardsAllies": "Team Player",
	"TD_OrbShare": "Orb Replicator",
	"TD_EnhancedOrbsCooldown": "Orb Ponderer",
	"TD_EnhancedOrbsSpeed": "Orb Dancer",
	"TD_KOKing": "Prize Fighter",
	"TD_TakeDownReduceCooldowns": "Adrenaline Rush",
	"TD_HitEnemyBurnThem": "Stinger",
	"TD_MultiHitsReduceCooldowns": "Heavy Impact",
	"TD_AvoidDamageHitHarder": "Glass Cannon",
	"TD_ComboATarget": "One-Two-Punch",
	"TD_DistancePower": "Deadeye",
	"TD_FasterProjectiles": "Missile Propulsion",
	"TD_FasterProjectiles2": "Aerials",
	"TD_FasterDashes3": "Explosive Entrance",
	"TD_FasterDashes": "Super Surge",
	"TD_EdgePower": "Knifes Edge",
	"TD_HitSpeed": "Fight or Flight",
	"TD_StrikeCooldownReduction": "Quick Strikes",
	"TD_HitsIncreaseSpeedAndPower": "Stacks on Stacks",
	"TD_ResistFirstHit": "Unstoppable",
	"TD_IncreasedSpeedWithStagger": "Stagger Swagger",
	"TD_BaseStaggerAndRegen": "Reptile Remedy",
	"TD_HitAnythingRestoreStagger": "Tempo Swing",
	"TD_EnergyCatalyst": "Catalyst",
	"TD_EnergyConversion": "Egoist",
	"TD_EnergyDischarge": "Fire Up",
	"TD_KnockAnythingRecoverStagger": "Vicious Vambrace",
    "TD_GoalArcPower": "Powerhouse Pauldrons",
    "TD_MovementAbilitiesTeleport": "Eject Button",
    "TD_IncreasedStatsWhileStaggered": "Berserker",
    "TD_IncreasedSpeedCrossingMidfield": "Magnetized Soles",
    "TD_HitCoreGainCDR": "Inner Focus",
    "TD_GainRampingSpeed": "Momentum Boots",
    "TD_StrikeRockSpeedUp": "Slick Kicks",
    "TD_RangedStrike": "Strike Shot",
    "TD_AvoidKnockoutGainSpeed": "Omega Infused Accelerator",
    "TD_HitStaggerEnemyCooldownReduction": "Pummelers",
    "TD_HitEnemyDrainThem": "Siphoning Wand"
}

in_rotation_trainings = {
	"TD_HitSpeed": "Fight or Flight",
	"TD_FasterProjectiles3": "Siege Machine",
	"TD_EnergyDischarge": "Fire Up",
	"TD_KOKing": "Prize Fighter",
	"TD_HitsIncreaseSpeedAndPower": "Stacks on Stacks",
	"TD_EmpoweredHitsBuff": "Specialized Training",
	"TD_PrimaryAbilityCooldownReduction": "Rapid Fire",
	"TD_FasterDashes2": "Chronoboost",
	"TD_SizePowerConversion": "Might of the Colossus",
	"TD_EdgePower": "Knifes Edge",
	"TD_EnhancedOrbsCooldown": "Orb Ponderer",
	"TD_BlessingPower": "Spark of Strength",
	"TD_Revive": "Recovery Drone",
	"TD_EnergyConversion": "Egoist",
	"TD_BlessingCooldownRate": "Spark of Focus",
	"TD_BlessingSpeed": "Spark of Agility",
	"TD_SizeIncrease": "Built Different",
	"TD_BarrierBuff": "Demolitionist",
	"TD_StaggerPowerConversion": "Bulk Up",
	"TD_StaggerSpeedConversion": "Peak Performance",
	"TD_CreationSizeLifeTime": "Timeless Creator",
	"TD_HitRockCooldown": "Hot Shot",
	"TD_StrikeRockTowardsAllies": "Team Player",
	"TD_HitEnemyBurnThem": "Stinger",
	"TD_MultiHitsReduceCooldowns": "Heavy Impact",
	"TD_AvoidDamageHitHarder": "Glass Cannon",
	"TD_DistancePower": "Deadeye",
	"TD_FasterProjectiles": "Missile Propulsion",
	"TD_FasterProjectiles2": "Aerials",
	"TD_FasterDashes3": "Explosive Entrance",
	"TD_BaseStaggerAndRegen": "Reptile Remedy",
	"TD_HitAnythingRestoreStagger": "Tempo Swing",
    "TD_IncreasedStatsWhileStaggered": "Berserker",
    "TD_AvoidKnockoutGainSpeed": "Omega Infused Accelerator",

    "TD_GoalArcPower": "Powerhouse Pauldrons",
    "TD_MovementAbilitiesTeleport": "Eject Button",
    "TD_GainRampingSpeed": "Momentum Boots",
    "TD_RangedStrike": "Strike Shot",
	"TD_KnockAnythingRecoverStagger": "Vicious Vambrace",
    "TD_IncreasedSpeedCrossingMidfield": "Magnetized Soles",
    "TD_StrikeRockSpeedUp": "Slick Kicks",
    "TD_HitStaggerEnemyCooldownReduction": "Pummelers",
    "TD_HitEnemyDrainThem": "Siphoning Wand"
}


training_tags = {
	"Built Different": ["Size", "Impact"],
	"Rampage": ["Size+Barrier"],
	"Demolitionist": ["Size", "CDR+Barrier"],
	"Bulk Up": ["Stagger", "Power"],
	"Peak Performance": ["Stagger", "Speed"],
	"Monumentalist": ["Creation"],
	"Timeless Creator": ["Creation"],
	"Siege Machine": ["Creation", "Projectile"],
	"Cast to Last": ["Buff", "Creation"],
	"Extra Special": ["CDR+Special"],
	"Specialized Training": ["Power+Special"],
	"Twin Drive": ["CDR+Secondary"],
	"Primetime": ["CDR+Primary"],
	"Hot Shot": ["CDR+Corespeed"],
	"Among Titans": ["Speed+!Size"],
	"Team Player": ["Corespeed"],
	"Orb Dancer": ["Speed+Orb"],
	"Prize Fighter": ["Power"],
	"Stinger": ["Damage"],
	"Heavy Impact": ["Impact+Power", "CDR+Multihit"],
	"Glass Cannon": ["Speed", "Power"],
	"One-Two-Punch": ["Power"],
	"Deadeye": ["Power+Range"],
	"Missile Propulsion": ["Projectile"],
	"Aerials": ["Dash"],
	"Explosive Entrance": ["Dash"],
	"Super Surge": ["Dash"],
	"Quick Strikes": ["Strike"],
	"Stacks on Stacks": ["Speed"],
	"Reptile Remedy": ["Stagger", "Healing"],
	"Tempo Swing": ["Healing", "Damage"],
	"Vicious Vambrace": ["Healing"],
    "Powerhouse Pauldrons": ["Size", "Power"],
    "Eject Button": ["Dash"],
    "Berserker": ["Power", "CDR"],
    "Magnetized Soles": ["Speed"],
    "Inner Focus": ["CDR"],
    "Momentum Boots": ["Speed"],
    "Slick Kicks": ["Speed"],
    "Strike Shot": [],
    "Omega Infused Accelerator": ["Speed"],
    "Pummelers": ["Power", "Speed"],
    "Siphoning Wand": ["Damage"]
}

character_negative_tags = {# im not gonna manually do this :(
    "Juliette": ["Projectile", "Range", "Creation", "Damage", "Buff"],
    "Estelle": ["Creation", "Damage", "Buff"],
    "Dubu": ["Damage", "Dash"],
    "Luna": ["Creation", "Buff", "Impact", "Multihit"],
    "Juno": [],
    "Asher": [],
    "Kai": [],
    "Era": [],
    "X": [],
    "Aimi": [],
    "Finii": [],
    "Zen": [],
    "Octavia": [],
    "Vyce": [],
    "Mako": [],
    "Rune": [],
    "Drek'ar": [],
    "Atlas": [],
    "Nao": [],
    "Rasmus": [],
    "Kazan": []
}

# for character in characters:
#     tags = character_negative_tags[character]
#     works = []
#     for training in in_rotation_trainings.values():
#         t_tags = training_tags[training]
        
#         for tag in t_tags:
#             parts = tag.split("+")
#             for part in parts:
#                 if part not in tags and training not in works:
#                     works.append(training)
#     print(character, works)

training_categories = {
    "Goalie":["Powerhouse Pauldrons","Eject Button","Momentum Boots","Strike Shot"],
    "Forward":["Slick Kicks", "Magnetized Soles", "Pummelers", "Siphoning Wand", "Vicious Vambrace"]
}