from BaseClasses import ItemClassification, Item

item_start_id = 1284190
item_map = {}
classification_table = {}


class ThePlanetCrafterItem(Item):
    game: str = "The Planet Crafter"


class PCItem:
    ID = item_start_id

    def __init__(self, name: str, classification: ItemClassification):
        self.name = name
        self.classification = classification
        self.item_id = PCItem.ID
        PCItem.ID += 1
        item_map[self.name] = self.item_id
        classification_table[self.name] = self.classification


items = [
    PCItem("CraftStation2", ItemClassification.progression),
    PCItem("WallWindow", ItemClassification.progression),
    PCItem("FloorGlass", ItemClassification.progression),
    PCItem("Vegetube2", ItemClassification.progression),
    PCItem("VegetubeOutside1", ItemClassification.progression),
    PCItem("Drill1", ItemClassification.progression),
    PCItem("Drill2", ItemClassification.progression),
    PCItem("Drill3", ItemClassification.progression),
    PCItem("Drill4", ItemClassification.progression),
    PCItem("EnergyGenerator2", ItemClassification.progression),
    PCItem("EnergyGenerator3", ItemClassification.progression),
    PCItem("EnergyGenerator4", ItemClassification.progression),
    PCItem("EnergyGenerator5", ItemClassification.progression),
    PCItem("EnergyGenerator6", ItemClassification.progression),
    PCItem("ScreenTerraStage", ItemClassification.progression),
    PCItem("Container2", ItemClassification.progression),
    PCItem("Backpack2", ItemClassification.progression),
    PCItem("Backpack3", ItemClassification.progression),
    PCItem("Backpack5", ItemClassification.progression),
    PCItem("Backpack6", ItemClassification.progression),
    PCItem("OxygenTank2", ItemClassification.progression),
    PCItem("OxygenTank3", ItemClassification.progression),
    PCItem("EquipmentIncrease2", ItemClassification.progression),
    PCItem("EquipmentIncrease3", ItemClassification.progression),
    PCItem("EquipmentIncrease4", ItemClassification.progression),
    PCItem("PulsarQuartz", ItemClassification.progression),
    PCItem("Seed0", ItemClassification.progression),
    PCItem("Heater2", ItemClassification.progression),
    PCItem("Heater3", ItemClassification.progression),
    PCItem("Heater4", ItemClassification.progression),
    PCItem("Heater5", ItemClassification.progression),
    PCItem("FabricBlue", ItemClassification.progression),
    PCItem("BedDouble", ItemClassification.progression),
    PCItem("Beacon1", ItemClassification.progression),
    PCItem("ComAntenna", ItemClassification.progression),
    PCItem("ScreenMessages", ItemClassification.progression),
    PCItem("Rod-alloy", ItemClassification.progression),
    PCItem("Rod-osmium", ItemClassification.progression),
    PCItem("Ladder", ItemClassification.progression),
    PCItem("OreExtractor1", ItemClassification.progression),
    PCItem("OreExtractor2", ItemClassification.progression),
    PCItem("OreExtractor3", ItemClassification.progression),
    PCItem("VegetableGrower1", ItemClassification.progression),
    PCItem("VegetableGrower2", ItemClassification.progression),
    PCItem("WaterCollector1", ItemClassification.progression),
    PCItem("GrassSpreader1", ItemClassification.progression),
    PCItem("SeedSpreader1", ItemClassification.progression),
    PCItem("SeedSpreader2", ItemClassification.progression),
    PCItem("Biolab", ItemClassification.progression),
    PCItem("AlgaeSpreader1", ItemClassification.progression),
    PCItem("AlgaeSpreader2", ItemClassification.progression),
    PCItem("WaterFilter", ItemClassification.progression),
    PCItem("Biodome1", ItemClassification.progression),
    PCItem("Biodome2", ItemClassification.progression),
    PCItem("ButterflyDome1", ItemClassification.progression),
    PCItem("WaterCollector2", ItemClassification.progression),
    PCItem("Jetpack4", ItemClassification.progression),
    PCItem("FusionEnergyCell", ItemClassification.progression),
    PCItem("RocketBiomass1", ItemClassification.progression),
    PCItem("RocketOxygen1", ItemClassification.progression),
    PCItem("RocketInsects1", ItemClassification.progression),
    PCItem("GasExtractor1", ItemClassification.progression),
    PCItem("GasExtractor2", ItemClassification.progression),
    PCItem("Mutagen2", ItemClassification.progression),
    PCItem("Mutagen3", ItemClassification.progression),
    PCItem("Mutagen4", ItemClassification.progression),
    PCItem("GeneticManipulator1", ItemClassification.progression),
    PCItem("ScreenRockets", ItemClassification.progression),
    PCItem("Tree3Seed", ItemClassification.progression),
    PCItem("Tree4Seed", ItemClassification.progression),
    PCItem("Tree5Seed", ItemClassification.progression),
    PCItem("Tree6Seed", ItemClassification.progression),
    PCItem("Tree9Seed", ItemClassification.progression),
    PCItem("Sign", ItemClassification.progression),
    PCItem("FlowerPot1", ItemClassification.progression),
    PCItem("TreeSpreader0", ItemClassification.progression),
    PCItem("TreeSpreader1", ItemClassification.progression),
    PCItem("TreeSpreader2", ItemClassification.progression),
    PCItem("Teleporter1", ItemClassification.progression),
    PCItem("Incubator1", ItemClassification.progression),
    PCItem("LarvaeBase1", ItemClassification.progression),
    PCItem("ScreenBiomass", ItemClassification.progression),
    PCItem("Beehive1", ItemClassification.progression),
    PCItem("Butterfly8Larvae", ItemClassification.progression),
    PCItem("Butterfly9Larvae", ItemClassification.progression),
    PCItem("Butterfly10Larvae", ItemClassification.progression),
    PCItem("Beehive2", ItemClassification.progression),
    PCItem("Farm1", ItemClassification.progression),
    PCItem("SilkGenerator", ItemClassification.progression),
    PCItem("ButterflyFarm1", ItemClassification.progression),
    PCItem("LarvaeBase3", ItemClassification.progression),
    PCItem("ButterflyDisplayer1", ItemClassification.progression),
    PCItem("Butterfly16Larvae", ItemClassification.progression),
    PCItem("Butterfly17Larvae", ItemClassification.progression),
    PCItem("AstroFood2", ItemClassification.progression),
    PCItem("AirFilter1", ItemClassification.progression),
    PCItem("AutoCrafter1", ItemClassification.progression),
    PCItem("ButterflyFarm2", ItemClassification.progression),
    PCItem("DroneStation1", ItemClassification.progression),
    PCItem("WaterLifeCollector1", ItemClassification.progression),
    PCItem("Fish1Eggs", ItemClassification.progression),
    PCItem("Fish3Eggs", ItemClassification.progression),
    PCItem("Fish5Eggs", ItemClassification.progression),
    PCItem("Fish6Eggs", ItemClassification.progression),
    PCItem("FishDisplayer1", ItemClassification.progression),
    PCItem("FrogDisplayer1", ItemClassification.progression),
    PCItem("CircuitBoard1", ItemClassification.progression),
    PCItem("Aquarium1", ItemClassification.progression),
    PCItem("Aquarium2", ItemClassification.progression),
    PCItem("FishFarm1", ItemClassification.progression),
    PCItem("AmphibiansFarm1", ItemClassification.progression),
    PCItem("Frog1Eggs", ItemClassification.progression),
    PCItem("Frog2Eggs", ItemClassification.progression),
    PCItem("Frog9Eggs", ItemClassification.progression),
    PCItem("Frog7Eggs", ItemClassification.progression),
    PCItem("Frog5Eggs", ItemClassification.progression),
    PCItem("Frog4Eggs", ItemClassification.progression),
    PCItem("Optimizer1", ItemClassification.progression),
    PCItem("Optimizer2", ItemClassification.progression),
    PCItem("GeneticExtractor1", ItemClassification.progression),
    PCItem("GeneticSynthetizer1", ItemClassification.progression),
    PCItem("LaunchPlatform", ItemClassification.progression),
    PCItem("PortalGenerator1", ItemClassification.progression),
    PCItem("PinChip1", ItemClassification.progression),
    PCItem("AnimalShelter1", ItemClassification.progression),
    PCItem("AnimalFeeder1", ItemClassification.progression),
    PCItem("DeparturePlatform", ItemClassification.progression),
    PCItem("RocketAnimals1", ItemClassification.progression),
    PCItem("Ecosystem1", ItemClassification.progression),
    PCItem("AnimalFood1", ItemClassification.progression),
    PCItem("AnimalFood2", ItemClassification.progression)
]
